name: DevOps CI Pipeline

on:
  push:
    branches:
      - main
      - feature-*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show files
        run: ls -la

      - name: Simulate build
        run: echo "Building application..."

      - name: Simulate tests
        run: echo "Running tests..."

      - name: Success message
        run: echo "Build and test completed"
